function Hd = Cheb_38_filter(fs, Fpass1, Fpass2)
%CHEB_38_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 06-Apr-2021 13:03:35

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.
N      = 38;   % Order
Apass  = 1;    % Passband Ripple (dB)

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, fs);
Hd = design(h, 'cheby1');

% [EOF]
